### ISSUE TITLE
Roadmap for `AllocRef`

### ISSUE THREAD

**Issue by TimDiekmann** [rust-lang/wg-allocators#48]
Currently, #38, #41, and #44 are [in the queue](https://github.com/rust-lang/rust/pull/69889). After this has (hopefully) landed I like to get to the listed issues in the specified order:

- [ ] #5: Support reallocating to a different alignment?
- [ ] #42: Shrinking should never fail) if possible/desired
- [ ] #37: Change the signatures of `AllocRef` to take `self` instead of `&mut self`
- [ ] #21: Coherent design of `GlobalAlloc` and `Alloc`
- [ ] #43: Implement `AllocRef` on `System` without `GlobalAlloc`
- [ ] #47: Allocation promises with global `AllocRef` allocator
- [ ] soft-deprecate, deprecate+hide, remove `GlobalAlloc`

**Comment by TimDiekmann** [comment]
Updated OP.

**Comment by Wodann** [comment]
@TimDiekmann what are next steps? Are we waiting for potential feedback from users on our changes to the API before we proceed?

**Comment by TimDiekmann** [comment]
I'm currently testing the API with [`alloc-compose`](https://crates.io/crates/alloc-compose). I also testing out, on how well taking `&self` is working. While most allocators *could* use `&self` instead of `&mut self` this has a major downside: `Cell` is `!Sync`, so using internal mutability for `Sync` allocators have to use atomics or other structs, which introduce more overhead. For the same reason, `Bump` from bumpalo is also `!Sync`.

**Comment by Amanieu** [comment]
I think those downside of `&self` are actually advantages, see #55.

**Comment by SimonSapin** [comment]
> * deprecate `GlobalAlloc`

Actively emitting deprecation warnings causes churn. What benefit does this bring in exchange?

> *add `#[doc(hidden)]` to `GlobalAlloc`

`GlobalAlloc` is stable, so there will always be legacy code that uses it (even if with deprecating warnings). Hiding its docs would be confusing to future readers of such code, for what benefit? Compared to documenting that using `AllocRef` instead is preferred.

**Comment by TimDiekmann** [comment]
Isn't that the point of deprecation warnings? `Error::source` was introduced in 1.30, `Error::cause` was deprecated in 1.33. I expect many more people to use the `Error` trait than the `GlobalAlloc` trait. Sure, we could also just leave `GlobalAlloc` alone :slightly_smiling_face: 

> Hiding its docs would be confusing to future readers of such code

Fair point.

**Comment by Wodann** [comment]
@TimDiekmann Could you update the roadmap with recent changes and what's left for us to do?

Also, can we proceed with #7 now that unstable generic trait instantiations are supported?

**Comment by TimDiekmann** [comment]
Updated the roadmap.

> Also, can we proceed with #7 now that unstable generic trait instantiations are supported?

rust-lang/rust#72314 is not merged yet as @Varkor asked for a few more tests. I will open a new issue for each collection when it's merged.

**Comment by Wodann** [comment]
Thanks for cleaning up the roadmap and outstanding issues 👍

**Comment by TimDiekmann** [comment]
@Wodann FYI: We have started to implement #7.

**Comment by berkus** [comment]
Should `AllocRef` be renamed `Allocator` now or it's a different AllocRef?

**Comment by TimDiekmann** [comment]
https://github.com/rust-lang/wg-allocators/issues/76
https://github.com/rust-lang/rust/pull/79286

**Comment by MarinPostma** [comment]
Hey I see that the last message in this issue is 3yo, what's the current status? Is there any way to get involved and help move the needle a bit?

**Comment by yanchith** [comment]
@MarinPostma If you use nightly, allocators are very much usable already (and have been since 2021-ish). I figure most people that need allocators already use them, and you can too.

You can make your own allocators and your own allocator-aware collections, and these days even most of alloc/std collections already work custom allocators (#7), with String<A> being the notable holdout (there's a history of attempts to make it happen, current HEAD here https://github.com/rust-lang/rust/pull/101551).

Regarding allocators on stable: if you look at issues in this repository, you'll see we are still a long way off. Personally, I'd want to have some kind of MVP stabilized sooner, possibly at the expense of completely resolving questions such as #15.

Regarding involvement: I don't know of any easy things that need doing. #7 was such a list, but fruit has been picked.

**Comment by wmmc88** [comment]
> Regarding allocators on stable: if you look at issues in this repository, you'll see we are still a long way off.

As a stopgap, I've seen many people adopt the use of https://github.com/zakarumych/allocator-api2 to get these apis in stable. This includes larger crates like [hashbrown](https://crates.io/crates/hashbrown)

**Comment by jmillikin** [comment]
In the spirit of seeking an MVP, is there anything blocking the stabilization of the "required" subset of `core::alloc::Allocator`?

For example, consider an `Allocator` with only two methods: `allocate()` and `deallocate()`. Are there any compatibility or stability concerns with stabilizing those two, and then leaving the optional methods for later?

```rust
pub unsafe trait Allocator {
    fn allocate(&self, layout: Layout) -> Result<NonNull<[u8]>, AllocError>;

    unsafe fn deallocate(&self, ptr: NonNull<u8>, layout: Layout);
}
```

The goal here would be to enable use of `Allocator` with third-party crates that do their own alloc management, e.g. for arenas or custom `Box`-like types.

**Comment by yanchith** [comment]
Like @jmillikin, I'd also like to see minimal subset stabilized, although my minimal subset is a little larger: 

As a user of allocator_api, I'd be quite happy with stabilizing a min_allocator_api with:

- The Allocator trait as is (except maybe `Allocator::by_ref`, but maybe I just don't understand what it is for).
- The allocator type parameter on std collections. I think this is almost implemented and the only critical thing missing is `String<A>`.
- Nothing else: no `vec_in!`, `DefaultIn`, `collect_in`, etc. The reasoning here is that if someone really needs custom allocators for better speed/memory, they will be okay without all these helpers. Additionally, I'd argue that in codebases where performance is important, these helpers obscure what is going on.

Anyway, the current allocator_api + `String<A>` would already be very useful to a lot of people.

Can some of the workgroup members and designers here comment on they think is needed?

**Comment by DemiMarie** [comment]
Yes please.

Enough time has passed, let’s get this merged.
