### ISSUE TITLE
Tracking Issue for structs which needs an allocator

### ISSUE THREAD

**Issue by TimDiekmann** [rust-lang/wg-allocators#7]
This WG wants to associate an allocator for all suitable structs. This issue tracks those structs, which are covered so far (non-exhaustive list):

- [ ] `Box<T, A>`: rust-lang/rust#77187
- [ ] `Rc<T, A>`
- [ ] `Arc<T, A>`
- [ ] `String<A>`
- [ ] `Vec<T, A>`: [alloc_wg](https://timdiekmann.github.io/alloc-wg/alloc_wg/vec/struct.Vec.html)
- [ ] `VecDeque<T, A>`
- [ ] `LinkedList<T, A>`
- [ ] `HashMap<K, V, S, A>`: TBD: in [hashbrown crate](https://github.com/Amanieu/hashbrown)?
- [ ] `BTreeMap<K, V, A>`: rust-lang/rust#77438
- [ ] `HashSet<T, S, A>`
- [ ] `BTreeSet<T, A>`
- [ ] `BinaryHeap<T, A>`
- [ ] (`CString<A>`)
- [ ] (`OsString<A>`)
- [ ] (`PathBuf<A>`)

**Comment by Ericson2314** [comment]
I've started in https://github.com/rust-lang/rust/pull/60703 .

**Comment by ErichDonGubler** [comment]
@obsidianminor has asked about the `Clone` trait needing to also be modified:

[(38183) Allocator aware std traits - rust-lang - Zulip](https://rust-lang.zulipchat.com/#narrow/stream/197181-t-libs.2Fwg-allocators/topic/Allocator.20aware.20std.20traits)

> There's a number of traits that implicitly allocate to the global allocator like `str` `ToOwned` making a `String<Global>` and `Clone` `String<Global>` always making another `String<Global>` which would make it slightly more difficult to move data across allocators.
> 
> ```rust
> let  a: String<Global>  =  format!("hello world!");
> let  b: String<System>  =  a.clone();  // nope, that's a String<Global>
> let  b: String<System>  =  {  // we could do it manually
>   let  mut  z: String<System>  =  String::new();
>   z.push_str(a.as_str());
>   z
> };
> let  b: String<System>  =  a.clone_in(System);  // or use a trait
> 
> let  s: &'static  str  =  "hello world!";
> let  t: String<Global>  =  s.to_owned();
> let  u: String<System>  =  s.to_owned();  // nope, it's Global again
> let  v: String<System>  =  s.to\_owned\_in(System);
> ```
> 
> Is there an issue yet talking about traits like this?

Any reason this issue couldn't also accomodate `Clone` and any other traits/method we think of along the way? :)

**Comment by lachlansneff** [comment]
Thoughts on `CloneIn: Clone` trait instead of adding an additional `clone_in` method to `Clone?

**Comment by ErichDonGubler** [comment]
@lachlansneff: What would your motivation be for splitting into another trait?

**Comment by lachlansneff** [comment]
@ErichDonGubler 

Adding it to `Clone` would be a breaking change. I can't think of a valid default implementation for `Clone::clone_in` and many types would have nothing to do with an allocator.

**Comment by TimDiekmann** [comment]
I think this should be added to the list in #15.
When implementing `Box` and `RawVec` I had to limit those traits to allocators, which implements `Default` which is rather limiting.

**Comment by TimDiekmann** [comment]
However, as @SimonSapin noticed in https://github.com/rust-lang/wg-allocators/issues/15#issuecomment-489595249, it's probably fine to add them at a later point. 
Additionally, if you really need those traits, I think a third party trait should be possible here until landed.

**Comment by ErichDonGubler** [comment]
Okay. I'm guessing it'd look something like this?

```rust
pub trait CloneIn {
    type Alloc: Alloc;

    fn clone_in(&self, allocator: Self::Alloc) -> T;
}
```

**Comment by Amanieu** [comment]
> Adding it to Clone would be a breaking change. I can't think of a valid default implementation for Clone::clone_in and many types would have nothing to do with an allocator.

Wouldn't just calling regular `clone` and ignoring the allocator be a valid default implementation?

**Comment by lachlansneff** [comment]
@Amanieu, I suppose that'd be valid, but it seems like very confusing behavior to me.

**Comment by lachlansneff** [comment]
@ErichDonGubler, I don't think it'd need a `Alloc` associated type, but it would need a generic self type I think.

```rust
pub trait CloneIn {
    type This<A: Alloc>;
    fn clone_in<A: Alloc>(&self, allocator: A) -> Self::This<A>;
}
```

This won't be possible until generic associated types, maybe there's another way of doing it?

**Comment by ObsidianMinor** [comment]
I was thinking something like
```rust
pub trait CloneIn<A: Alloc> {
    type Cloned;

    fn clone_in(&self, allocator: A) -> Self::Cloned;
}
```
Then you can implement it like
```rust
impl<S, A: Alloc> CloneIn<A> for String<S> {
    type Cloned = String<A>;

    fn clone_in(&self, allocator: A) -> Self::Cloned {
        String { vec: self.vec.clone_in(allocator) }
    }
}
```

**Comment by TimDiekmann** [comment]
I had this in mind:
```rust
pub trait CloneIn<B: BuildAllocRef>: Sized
where
    B::Ref: AllocRef,
{
    fn clone_in(&self, a: B::Ref) -> Self
    where
        B::Ref: AllocRef<Error = crate::Never>;

    fn try_clone_in(&self, a: B::Ref) -> Result<Self, <B::Ref as AllocRef>::Error>;
}
```

I think this should be discussed in #15 or a new Issue.

**Comment by gnzlbg** [comment]
@Amanieu 

> Wouldn't just calling regular clone and ignoring the allocator be a valid default implementation?

How would you add this method to `Clone` ? (*)

IIUC what you are proposing, what would something like this do

```rust
let x: Vec<T, A>;
let y: Vec<T, U> = x.clone_in();
```

if `Clone::clone_in` is implemented on top of `clone` ?

(*) I can imagine that we either have `Clone<A> for T` which would be a breaking change, or `Clone::clone_in<Other>(&self) -> Other where Self: Sized` or something like that, but I'm probably missing some more obvious extension.

**Comment by gnzlbg** [comment]
@95th You would need to return a different type than `Self` to be able to clone a `Box<T, A>` into one that has a different type because it has a different allocator, e.g.,  `Box<T, B>`.

**Comment by 95th** [comment]
@gnzlbg you're right sorry.. A type based on generic param

**Comment by lqf96** [comment]
Do we also need to associate an allocator for owned strings types from `std::ffi` module? That will include `CString` and `OSString`...

**Comment by TimDiekmann** [comment]
On Sonntag, 10. November 2019 23:23:43 CET Qifan Lu wrote:
> Do we also need to associate an allocator for owned strings types from
> `std::ffi` module? That will include `CString` and `OSString`...

Adding an associated allocator to `CString` should be pretty straightforward, 
as it's basically a `Box<[u8]>`. `OSString` depends on the Os, but this 
shouldn't be a problem as well. Based on this, also `PathBuf` may should get 
an allocator, too. All three have a low priority at time of writing though.

**Comment by TimDiekmann** [comment]
Currently, there is a PR upstream for `Box` and `BTreeMap`. After `Box` is merged, I'll adjust `Vec`.

cc @exrook

**Comment by pickfire** [comment]
When can we put `Vec<T, A>` into std? I keep track of vec more than the rest, maybe I can help out with vec?

**Comment by TimDiekmann** [comment]
I just answered the question right above. And my fat fingers clicked the wrong button :D

**Comment by TimDiekmann** [comment]
rust-lang/rust#77187 just got merged. I'll add an allocator parameter to `Vec` next.

**Comment by hansihe** [comment]
https://github.com/rust-lang/hashbrown/pull/133 got merged a few days ago, adding custom allocator support to hashbrown.

Would this working group be willing to accept a PR for the std `HashMap` and `HashSet` too, or is it too early?

**Comment by TimDiekmann** [comment]
Forwarding to `hashbrown` should be pretty straightforward. Currently, `Vec` is queued for a crater run and this will take a while. I can take a look at `HashMap` (+ `HashSet`, which is basically the same) afterwards. Thanks for the heads up!

**Comment by lqf96** [comment]
@TimDiekmann It seems like efforts to add allocator to `CString` has stalled due to issues with generic parameter stability attributes... Would it be a good idea to turn to other data structures first, such as `HashMap` and `HashSet` suggested by @hansihe, while waiting for someone to fix the issue?

**Comment by TimDiekmann** [comment]
There is an open proposal #79 which would replace the allocator backend with a storage backend, which is more flexible and intuitive. This is looking very promising and I'd prefer that in favor of adding allocators to every data structure. Since recently it is in a state with which it seems worth experimenting within std.

**Comment by cmazakas** [comment]
Is there interest in accepting contributions implementing Allocators for the various remaining containers? I'd like to try and help knock some of those out.

**Comment by TimDiekmann** [comment]
Yes, very much! Since I am currently relocating, I currently have only limited time.

**Comment by cmazakas** [comment]
Awesome! Alright, I've got the rust repo cloned and will be making an `rc-alloc` branch.

Anything I should know/adhere to going forward?

**Comment by SimonSapin** [comment]
https://rustc-dev-guide.rust-lang.org/contributing.html#contributing-to-rust should be a good start

**Comment by pickfire** [comment]
After reading into that, use `./x.py setup` to configure it for libs so you don't have to rebuild the whole compiler and for it to automatically download it online, that will make the development process much faster. I think the docs mention it somewhere but you need to find it, maybe you can just run that. After that you can start iterating on the libs. You might want to pick something simpler such as `Rc` first. Usually you only want `./x.py check` or it might take a long time if you do `./x.py test` or `./x.py build`, at the end you might want to write some tests and do `./x.py test --bless` to automatically fix the tests for you, you might also want to do test filtering.

**Comment by mark-i-m** [comment]
https://rustc-dev-guide.rust-lang.org/getting-started.html?highlight=setup#configuring-the-compiler may also be useful. The rustc-dev-guide is kind of geared towards the compiler itself, but a lot of the advice also applies to the standard library.

**Comment by a1phyr** [comment]
@TimDiekmann I have just sent a PR for `VecDeque`, could you add it to the top-level list ?

**Comment by Cyborus04** [comment]
@TimDiekmann I made a PR for `Rc` in rust-lang/rust#89132, could you add that to the list?

**Comment by yanchith** [comment]
I might have a usecase for `BinaryHeap` with custom allocators. Looking at the source, `BinaryHeap` is just a wrapper around `Vec`, which is already allocatorized, so extending it to support allocator api should be relatively straightforward.. I hope.

I notice there is no linked issue. If I want to add this, should I create an issue in `rust-lang/rust` and go from there?

**Comment by Amanieu** [comment]
I think you can just go ahead and write a pull request for it. All the allocators are under the #32838 tracking issue.

**Comment by rytheo** [comment]
@TimDiekmann I have a PR for `LinkedList` here: https://github.com/rust-lang/rust/pull/103093

**Comment by TimDiekmann** [comment]
Thanks, updated!

**Comment by yanchith** [comment]
Oh, I didn't realize I had to post back here, but I made a PR for `BinaryHeap` some time ago, but it looks like it got buried https://github.com/rust-lang/rust/pull/99339

**Comment by tgross35** [comment]
There are a few changes to the list in the issue - @TimDiekmann would you want to update these items?

- String<A>: new PR, blocked(?) https://github.com/rust-lang/rust/pull/101551
- LinkedList<T, A>: completed, will be available in 1.71
- BTreeMap<K, V, A>: new PR, completed https://github.com/rust-lang/rust/pull/98103
- BTreeSet<T, A>: new PR, completed https://github.com/rust-lang/rust/pull/98103
- BinaryHeap<T, A>: new PR, awaiting review as @yanchith mentioned, https://github.com/rust-lang/rust/pull/99339

**Comment by TimDiekmann** [comment]
Thank you, I updated the comment.

**Comment by tgross35** [comment]
Rc and Arc just landed! https://github.com/rust-lang/rust/pull/89132#event-9843774823
